language: node_js
sudo: required
node_js:
- 11.15.0
branches:
  only:
  - master
cache:
  yarn: true
install:
- yarn global add travis-ci-cloudfront-invalidation
- yarn install
script: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_S3_ACCESS_KEY
  secret_access_key: $AWS_S3_SECRET_KEY
  bucket: blog.kalob.net
  skip_cleanup: true
  local-dir: build
  acl: public_read
  region: us-east-2
  on:
    repo: PorterK/kalob.net-blog
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_CLOUDFRONT_ACCESS_KEY -s $AWS_CLOUDFRONT_SECRET
  -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
