language: node_js
sudo: required
node_js:
- 11.15.0
branches:
  only:
  - master
cache:
  yarn: true
install:
- yarn global add travis-ci-cloudfront-invalidation
- yarn install
script: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_S3_ACCESS_KEY
  secret_access_key: $AWS_S3_SECRET_KEY
  bucket: blog.kalob.net
  skip_cleanup: true
  local-dir: build
  acl: public_read
  region: us-east-2
  on:
    repo: PorterK/kalob.net-blog
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_CLOUDFRONT_ACCESS_KEY -s $AWS_CLOUDFRONT_SECRET
  -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
env:
  global:
    secure: y9ntZfaWYHJGj8pEyGQ6jBurP2u1U1EyD/G16cEOcUgQqaJUwg7p5zauvX6bZUB80RdRmoS4niIygp+eNuMW3oJYtqa5d6CaNkcFKl+yJ0zpjJvx0YgHbNuSEaQ3ffGLf6HppjVmmlJ5YkmVinvXVD34zHjvSiEDZz8n3KevX9THCDP3nyUWI/IMjWnYJfkFQg3q0wsVz+D+oXR/hz/FczeCyxiCySe3WShTWVa2/ADysXvaTajDifd76iPbHpvzEyLZM51eiMNA8o0tQ3b+k2is7eILutv+s06VwUpXSbA5Anr8U4FJlFY/cDJfxX4aoVPn4wtGk7K7LxD/jCvXdDrvwMxb34BmwucUORf6a130DUu5OOVYDMuW5OzAGr1wBNGQErYZCy1eJgz0ltO/iUfL1GbD8HtFS56CE0LtHr/l5RPI9FyXJu34lP95tHJ0FgfSvCFrC+6a1FvUrDn9voALHJ4bv88urp5Br7/MODEliK8V2GuqTLpEYsJlGcEdMD4ij4OFhiVmpJLB+XBp5tO9FDh3VTIPV+HPyJ0Y0ze+fRgukN3dblxgPDPw/IfPRFgNVL11rzAv9PTtnDBvHZbUKfltcFHsjmUibP0XQXtW9RNNoPzDE1mHwOnvQBc5cbHUuTpvfHnOnETiPh72iy05OmWK1HB8bcN5Jssaltc=
